---
driver:
  name: docker
  use_sudo: false

# If you add new platforms below, include them in the .travis.yml file matrix
platforms:
- name: centos-6
- name: centos-7
- name: debian-6
- name: debian-7
- name: debian-8
- name: fedora-20
- name: fedora-21
- name: oraclelinux-6
  driver_config:
    platform: rhel
- name: oraclelinux-7
  driver_config:
    platform: rhel
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-14.10
- name: ubuntu-15.04
